// Plain-English legal copy shared by the app pages (and mirrored in the demo).
// NOT LEGAL ADVICE and NOT a substitute for a licensed attorney's review — the
// liability/warranty language below aims for the maximum protection the law
// allows a peer-to-peer venue, but enforceability varies by state (implied-
// warranty disclaimers, injury/gross-negligence carve-outs, consumer-protection
// statutes). Have a lawyer review before launch, especially given tires are a
// safety-critical good.

export const LAST_UPDATED = "July 9, 2026";

export const TERMS = [
  ["What TireTrader is", "TireTrader is a marketplace that connects local buyers and sellers of new and used tires. We are not a party to any transaction — buyers and sellers arrange payment and pickup directly. We don't inspect, store, ship, or guarantee any tires."],
  ["Your account", "You must provide accurate information and keep your password secure. You're responsible for activity under your account. One person per account; you must be able to form a binding contract to use the service."],
  ["Listings & conduct", "Sellers are responsible for the accuracy of their listings and for the legality and condition of what they sell. Don't post counterfeit, stolen, unsafe, or prohibited items, spam, or anything misleading. Don't harass other users or try to take deals off-platform to defraud someone."],
  ["Buying & safety", "Inspect tires in person before paying, meet in a safe public place, and never pay before you've seen the goods. We surface tread, DOT year, and condition to help you vet listings, but you buy at your own risk."],
  ["Fees", "Browsing is free. Sellers may subscribe for a monthly fee (first year free). Fees are described at sign-up and may change with notice."],
  ["Moderation", "We may hide or remove listings, and suspend or remove accounts, that violate these terms or that we believe are harmful — including automatically when a listing is reported multiple times."],
  ["No warranties", "TireTrader is a venue, not a seller, dealer, inspector, or certifier of tires. The service and every listing are provided \"AS IS\" and \"AS AVAILABLE,\" without warranties of any kind, whether express or implied — including any implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement — to the fullest extent permitted by law. We do not inspect, test, certify, or guarantee any tire's condition, age, safety, legality, or fitness for any vehicle or use."],
  ["Used tires — assumption of risk", "Tires are a safety-critical part. Buying used tires carries inherent risk: hidden damage, age-related failure, improper prior repair, and mismatched or worn specifications can cause loss of control, injury, or death. You accept and assume all of that risk. Have any tire inspected and installed by a qualified professional before use, and follow the buying checklist. To the fullest extent permitted by law, you release TireTrader from all claims arising out of a tire's condition, age, defect, installation, or failure."],
  ["Limitation of liability", "To the fullest extent permitted by law, TireTrader and the people who operate it will not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any personal injury, death, or property damage, arising out of the service or any transaction between users. Our total liability for any claim will not exceed the greater of the fees you paid us in the 12 months before the claim or US $100. Some places don't allow certain limits, so parts of this section may not apply to you — nothing here limits liability that cannot be limited by law. This limit applies even if a limited remedy fails its essential purpose."],
  ["Indemnification", "You agree to defend, indemnify, and hold TireTrader harmless from any claim, loss, or expense (including reasonable legal fees) arising from your listings, your transactions, your content, or your violation of these terms or the law."],
  ["Severability", "If any part of these terms is found unenforceable, that part will be limited or removed to the smallest extent necessary, and the rest of the terms will stay in full effect."],
  ["Governing law", "These terms are governed by the laws of the State of Florida, without regard to its conflict-of-laws rules. Except for disputes subject to arbitration below, any dispute must be brought only in the state or federal courts located in Florida, and you consent to their jurisdiction and venue."],
  ["Arbitration & class-action waiver", "This agreement affects interstate commerce and is governed by the Federal Arbitration Act. Most disputes between you and TireTrader will be resolved by BINDING INDIVIDUAL ARBITRATION rather than in court, under the American Arbitration Association's Consumer Arbitration Rules — except that either party may bring a qualifying claim in small-claims court. TireTrader will pay the AAA filing and arbitrator fees that the Consumer Arbitration Rules require it to pay. YOU AND TIRETRADER WAIVE THE RIGHT TO A JURY TRIAL AND THE RIGHT TO BRING OR PARTICIPATE IN A CLASS, COLLECTIVE, OR REPRESENTATIVE ACTION; disputes are handled only on an individual basis. You may opt out of this arbitration agreement within 30 days of first accepting these terms by emailing arbitration-optout@tiretrader.com with your name and the email address on your account; opting out does not affect the rest of these terms. Notwithstanding the Severability section above, if the class-action waiver is found unenforceable for a particular dispute, this entire arbitration section is void as to that dispute (and that dispute proceeds in court)."],
  ["Changes", "We may update these terms; continued use means you accept the changes."],
];

export const PRIVACY = [
  ["What we collect", "Account info you provide (name, email, optional city/state, password — stored only as a secure hash), the listings, messages, favorites, saved searches, and reviews you create, and basic technical data like your IP (used for rate-limiting and abuse prevention) and approximate location only if you opt into \"near me\"."],
  ["How we use it", "To run the marketplace: show your listings, deliver messages, power search and local results, prevent fraud and abuse, and send account-related email (e.g., password resets)."],
  ["What we share", "Your public profile (name, location, ratings) and your listings are visible to other users. We don't sell your personal data. We use a small number of service providers (hosting, database, email, image storage) solely to operate the service."],
  ["Cookies", "We use a single essential, httpOnly session cookie to keep you logged in. No advertising or third-party tracking cookies."],
  ["Your controls", "You can export all your data or delete your account at any time from Settings. Deletion is reversible for 7 days, then permanent. You can also log out of all devices and change your password there."],
  ["Security", "Passwords are hashed, sessions are signed and revocable, uploads are validated and stripped of location metadata, and access to your messages is restricted to the participants."],
  ["Contact", "Questions about your data? Reach out via the email on your account."],
];
